### ISSUE TITLE
:lady_beetle: Bug:  Virtual machine: xxxx has an invalid Machine type: scale-bios-9.3.

### ISSUE THREAD

**Issue by ddemlow** [ScaleComputing/HyperCoreAnsibleCollection#299] opened 2024-03-28 17:41 UTC
## Describe the bug

**To Reproduce**
this VM was created using ansible collection - with machine type set to BIOS like in this example.  problem so far has been reproduced on 9.3.5 hypercore and 9.4.1 - will need some research on which specific versions of hypercore are impacted. 

    - name: Create "{{ image_name }}" template vm if it does not already exist 
      scale_computing.hypercore.vm:
        vm_name: "{{ image_name }}"
        description: "{{ image_url[0] }} template "
        state: present
        tags:
          - template
          - serial
        memory: "{{ '1 GB' | human_to_bytes }}"
        vcpu: 0 # makes template vm unbootable - must change cpu on cloned vm 
        power_state: stop
        disks:
          - type: ide_cdrom
            disk_slot: 0
          # - type: nvram
          #   disk_slot: 0
        nics:
          - vlan: 0
            type: virtio
        operating_system:  os_other
        machine_type: BIOS

root@demo3-pullrunner-jammy:~/.ansible/pull/demo3-pullrunner-jammy# ansible -i localhost, --connection=ansible.builtin.local all -m scale_computing.hypercore.vm_info
localhost | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "msg": "Virtual machine: sidero-3 has an invalid Machine type: scale-bios-9.3."
}

## Expected behavior
VM's created with BIOS machine type should map to an appropriate api level machine type 

## System Info (please complete the following information):
 - HyperCore Version:   9.3.5
 - Ansible Version:  [core 2.16.5]
 - Collection Version - 1.3.0

## Additional context
I know there have been a lot of changes to machine type from 9.2 to 9.3. to 9.4 - will need scale pm / eng to help sort this out

**Comment by shoriminimoe** [comment] 2024-03-28 18:08
This is a duplicate of #262. It is fixed by #267.

**Comment by ddemlow** [comment] 2024-03-28 18:52
fixed in 1.4.0

**Closed** 2024-03-28 18:52 UTC
Labels: bug
